name: Skyvo
favicon: null
layout_spectrum: 0.5137170271482319
typography_spectrum: 0.06254851096309721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.042219864670187235
  lightness: 0.24422357860021293
  saturation: 0.587532562436536
  rhythmicContrast: 0.9017048636451364
purpose: []
